config/routes.rb
Rails.application.routes.draw do

  get 'contacts/index'
  get 'contacts/show'
  get 'works/index'
  get 'about/index'
  get 'about/show'
  root to: 'home#index'
  get 'home/index'

  resources :homes

end

app/models/about.rb
class About < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/home.rb
class Home < ApplicationRecord
    mount_uploader :image, ImageUploader
end

app/models/work.rb
class Work < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
    end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/about/index.html.erb
<section class="container index">
<h1>About Me</h1>
<div class="intro_box">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <%= image_tag 'UNADJUSTEDNONRAW_thumb_17.jpg', class: 'd-block w-100' %>
      </div>
      <div class="carousel-item">
        <%= image_tag 'UNADJUSTEDNONRAW_thumb_15.jpg', class: 'd-block w-100' %>      
      </div>
      <div class="carousel-item">
        <%= image_tag 'UNADJUSTEDNONRAW_thumb_4.jpg', class: 'd-block w-100' %>
      </div>
    </div>
    
    <div class="self_intro">
      <p>こんにちは！生まれも育ちも大阪、Shirasaka-Takahiro(<a href="https://www.twitter.com/daikyoukin913" target="_blank">@daikyoukin913</a>)です！</p>
      <p>現在、webプログラマーを目指して楽しみながら勉強しています。言語は、Ruby on Railsを中心に、HTML, CSS, JavaScriptをスクールに通わず、六月から完全独学で勉強しています。</p>
      <p>好きなものは、プログラミング、英語、筋トレ、猫です。特に、英語と筋トレは大学生から毎日続けており、現在も英検一級合格に向けて日々勉強しています。</p>
      <p>現在までに３つのwebアプリを作成しており、当サイトより閲覧可能となっております！</p>
      <p>もし、質問などがありましたら、SNSもしくはコンタクトフォームよりご連絡ください。</p>
      <p>最後まで読んで頂き、ありがとうございました！</p>
    </div>
    
    <h1>Skills</h1>
    <div class="skills">
      <div class="row">
        <div class="col-xs-12 col-md-3"><%= icon("fas", "gem", class: "font")%>
          <p class="font_name">Ruby(Ruby on Rails)</p>
        </div>
        <div class="col-xs-12 col-md-3"><%= icon("fab", "html5", class: "font")%>
          <p class="font_name">HTML5</p>
        </div>
        <div class="col-xs-12 col-md-3"><%= icon("fab", "sass", class: "font")%>
          <p class="font_name">Sass</p>
        </div>
        <div class="col-xs-12 col-md-3"><%= icon("fab", "js", class: "font")%>
          <p class="font_name">JavaScript</p> 
        </div>     
      </div>
    </div>
    
  </div>


</div>
</section>

app/views/contacts/index.html.erb
<h1>Contact</h1>
<div class="contact_intro text-center">
  <%= icon("far", "paper-plane", class: "paper_plane") %>
  <p>当サイトを訪れていただきまして誠にありがとうございます。</p>
  <p>
    現在転職活動を行っております。未経験ではありますが、六月からの約半年間毎日プログラミングを楽しみながら独学で学んでおります。
  </p>
  <p>
    また、英語にも精通しており、大学1年生から今日に至るまで毎日英語に触れております。なので、英語に対応したWebアプリやWebサイトの作成も可能となっております。
  </p>
  <p>質問などがございましたら、下記のフォームもしくはSNS(下記アイコン)よりご連絡ください。</p>
</div>
<div id="formWrapper">
  <form action="https://docs.google.com/forms/u/0/d/e/1FAIpQLSe8XQt-AjGeR18K7vvykrMkHmjiTGLiEi2OuRuVlTkLhEu2Qw/formResponse" method="post" name="myForm" target="dummyIframe">
    <div class="contact_box">
      <label>お名前</label>
      <br>
      <input type="text" name="entry.2005620554" placeholder="山田 太郎" required/>
    </div>
    <div class="contact_box">
      <label>メールアドレス</label>
      <br>
      <input type="mail" name="entry.1045781291" placeholder="mail@example.com" required/>
    </div>
    <div class="contact_box">
      <label>質問・ご要望</label>
      <br>
      <textarea name="entry.839337160" placeholder="質問やご要望について" required></textarea>
    </div>
    <input class="btn btn-secondary" type="button" value="送信" onclick="submitForm()"/>
  </form>
  <iframe name="dummyIframe" style="display:none;"></iframe>
</div>
<div id="thxMessage" class="text-center" style="display:none;" >
  <p>お問い合わせありがとうございました。</p>
  <%= image_tag 'UNADJUSTEDNONRAW_thumb_18.jpg', class: 'contact_image' %>
</div>
<script>
  function submitForm(){
    document.myForm.submit();
    document.getElementById('formWrapper').style.display = 'none';
    document.getElementById('thxMessage').style.display = 'block';
  }
</script>

app/views/home/index.html.erb
<section class="index">
<div class="home_box">
  <%= image_tag 'olia-gozha-J4kK8b9Fgj8-unsplash.jpg', class: 'd-block w-100 image' %>
  <div class="inner_box">
	<h3 class="name">Shirasaka-Takahiro</h3>
    <p class="about_me"><%= link_to 'About me', about_index_path, class: 'btn' %></p>
  </div>
</div>

<!-- Portfolio start -->

<div class="fadein">
  <h1>Works</h1>
	<section id="work" class="module module-gray">
		<div class="container text-center">
			<div class="row">

				<div class="module-header wow fadeInUp">
					<h2 class="module-title"></h2>
					<div class="module-line"></div>
				</div>

			</div><!-- .row -->

			<!-- Portfolio Filter start-->

			<div class="row">

				<div class="col-sm-12">

					<ul id="filter" class=" wow fadeInUp">
						<li class="active" data-group="all">All</li>
						<li data-group="slideshow">Slideshow</li>
						<li data-group="video">Video</li>
						<li data-group="image">Image</li>
					</ul>

				</div>

			</div><!-- .row -->

			<!-- Portfolio Filter end -->

			<ul class="list-items-container">
            <div class="row">

				<li class="list-item" data-groups="all slideshow" targrt="_blank">
				  <p class="list-item-title">勤怠管理アプリ 「kintaikun」</p>
					<figure>
                        <%= image_tag 'スクリーンショット 2020-02-03 13.04.56.png' %>
						<figcaption>
							<a href="http://www.kintaikun.xyz/" target="_blank" class="simple-ajax-popup"></a>
							<div class="caption-inner">
								<h3 class="portfolio-item-title">kintaikun</h3>
							</div>
						</figcaption>
					</figure>
				</li>

				<li class="list-item" data-groups="all slideshow" targrt="_blank">
				  <p class="list-item-title">写真投稿アプリ 「Homeru」</p>
					<figure>
                        <%= image_tag 'スクリーンショット 2020-01-03 4.10.29.png' %>
						<figcaption>
							<a href="https://homeru913.herokuapp.com" target="_blank" class="simple-ajax-popup"></a>
							<div class="caption-inner">
								<h3 class="portfolio-item-title">Homeru</h3>
							</div>
						</figcaption>
					</figure>
				</li>

				<li class="list-item" data-groups="all video">
				  <p class="list-item-title">チャットアプリ 「E-Chat」</p>
					<figure>
                         <%= image_tag 'スクリーンショット 2020-01-03 4.11.16.png' %>
						<figcaption>
							<a href="https://e-chat111.herokuapp.com" target="_blank" class="simple-ajax-popup"></a>
							<div class="caption-inner">
								<h3 class="portfolio-item-title">E-Chat</h3>
							</div>
						</figcaption>
					</figure>
				</li>

				<li class="list-item" data-groups="all image">
				  <p class="list-item-title">記事投稿アプリ 「Media_a」</p>
					<figure>
                        <%= image_tag 'スクリーンショット 2020-01-03 4.12.48.png' %>
						<figcaption>
							<a href="https://mediaf.herokuapp.com " target="_blank" class="simple-ajax-popup"></a>
							<div class="caption-inner">
								<h3 class="portfolio-item-title">Media_A</h3>
							</div>
						</figcaption>
					</figure>
				</li>

        </div>
			</ul><!-- .projects-container -->

		</div><!-- .contaier -->
	  <p class="text-center">画像をタッチすると、それぞれのサイトへ移動します！</p>
    </section>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Portfolio</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js"></script>
  </head>

  <body>

  <div class="whole_body">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top">
    <a class="navbar-brand" href="/home/index">Shirasaka-Takahiro</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav ml-auto">
        <%= link_to 'Home', root_path, class: 'nav-item nav-link' %>        
        <%= link_to 'About me', about_index_path, class: 'nav-item nav-link' %>
        <%= link_to 'Works', works_index_path, class: 'nav-item nav-link' %>
        <%= link_to 'Contact', contacts_index_path, class: 'nav-item nav-link' %>        
      </ul>
    </div>
  </nav>

    <%= yield %>
  
  <div class="contact_page">
    <%= link_to icon("fas", "envelope", class: "icon"), contacts_index_path unless current_page?(contacts_index_path) %> 
          <a href="https://www.twitter.com/daikyoukin913" target="_blank">
            <%= icon("fab", "twitter-square", class: "icon") %>
          </a>
          <a href="https://www.facebook.com/takahiro.shirasaka.146" target="_blank">
            <%= icon("fab", "facebook-square", class: "icon") %>
          </a>
          <a href="https://www.instagram.com/shirasaka3015/" target="_blank">
            <%= icon("fab", "instagram", class: "icon") %>
          </a>
  </div>

  <div class="footer">
    <div class="copy text-center">&copy;Shirasaka-Takahiro All Right Reserved</div>
  </div>
  </div>

  <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/works/index.html.erb
<h1>Works</h1>

<section class="works_index">
  <div class="kintaikun content">
    <div class="row">
      <%= image_tag 'スクリーンショット 2020-02-03 13.04.56.png', class: 'works_image db-block w-100' %>
      <div class="explanation">
          <h3>『Kintaikun』</h3>
          <p>・勤怠管理アプリ</p>
          <p>・1月13日-1月31日</p>
          <p>・制作期間 約３週間</p>
          <p>・コンセプトは『楽するためのアプリ』</p>
          <p>・各月のイベント、時間（分、時間）を計算できるようにしました。</p>
          <p>・デプロイはAWSで行い、ドメインを変更しました。</p>
          <p>・分から時間への変換、少数以下の表示に苦戦しました。</p>
          <p><a href="http://www.kintaikun.xyz/" target="_blank">アプリに移動</a></p>
      </div>
    </div>
  </div>
  <div class="homeru content">
    <div class="row">
      <%= image_tag 'スクリーンショット 2020-01-03 4.10.29.png', class: 'works_image db-block w-100' %>
      <div class="explanation">
          <h3>『Homeru』</h3>
          <p>・写真投稿アプリ</p>
          <p>・12月21日-12月31日</p>
          <p>・制作期間 10日</p>
          <p>・コンセプトは『褒めてもらえる場所を作る』</p>
          <p>・コメントにNGワードの設定、お気に入り機能などはログイン後にしかできないようにしました。</p>
          <p>・投稿ソート、検索機能の実装に苦戦しました。</p>
          <p><a href="https://homeru913.herokuapp.com" target="_blank">アプリに移動</a></p>
      </div>
    </div>
  </div>
  <div class="E-Chat content">
    <div class="row">
      <%= image_tag 'スクリーンショット 2020-01-03 4.11.16.png', :rel => "lightbox", class: 'works_image db-block w-100'  %>
      <div class="explanation">
        <span>
        <h3>『E-Chat』</h3>
        <p>・チャットアプリ</p>
        <p>・11月中旬~</p>       
        <p>・制作期間 約３週間</p>
        <p>・コンセプトは『誰でも参加できるチャットスペース』</p>
        <p>・チャットルームの作成、管理者ユーザーにのみルーム削除権限を付けました。</p>
        <p>・Actioncableの機能把握、Ajaxとturbolinksの仕様理解に時間がかかりました。</p>
        <p><a href="https://e-chat111.herokuapp.com" target="_blank">アプリに移動</a></p>
        </span>
      </div>
    </div>
  </div>
  <div class="media_a content">
    <div class="row">
      <%= image_tag 'スクリーンショット 2020-01-03 4.12.48.png', class: 'works_image db-block w-100'  %>
       <div class="explanation">
        <span>
        <h3>『MediA』</h3>
        <p>・写真投稿アプリ</p>
        <p>・10月初旬~</p>
        <p>・制作期間 約１ヶ月</p>
        <p>・コンセプトは『シンプルな記事投稿サイト』</p>
        <p>・基本的なCRUD機能、画像アップロード機能などを実装しました。</p>
        <p>・CRUDの動き、メソッドなど基本的なもの全てに苦戦しました。</p>
        <p><a href="https://mediaf.herokuapp.com" target="_blank">アプリに移動</a></p>
        </span>
      </div>
    </div>
  </div>
</section>